package database.classes;
// Generated 19-May-2016 11:52:48 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Gamesession generated by hbm2java
 */
public class Gamesession  implements java.io.Serializable {


     private Integer id;
     private Date dato;
     private Scenario scenarioId;
     private Player registrar;
     private Integer orgId;
     private Game spillet;
     private Set<Participation> deltakelser = new HashSet<Participation>(0);

    public Gamesession() {
    }

    public Gamesession(Game spillId, Date dato, Scenario scenarioId, Player registrar, Integer orgId) {
       this.spillet = spillId;
       this.dato = dato;
       this.scenarioId = scenarioId;
       this.registrar = registrar;
       this.id = orgId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Game getSpillet() {
        return this.spillet;
    }
    public void setSpillet(Game spillId) {
        this.spillet = spillId;
    }    
    
    public void setDeltakelser(Set<Participation> lis) {
        this.deltakelser = lis;
    }
    public Set<Participation> getDeltakelser() {
        return this.deltakelser;
    }    
    
    public Date getDato() {
        return this.dato;
    }
    
    public void setDato(Date dato) {
        this.dato = dato;
    }
    public Scenario getScenarioId() {
        return this.scenarioId;
    }
    
    public void setScenarioId(Scenario scenarioId) {
        this.scenarioId = scenarioId;
    }
    public Player getRegistrar() {
        return this.registrar;
    }
    
    public void setRegistrar(Player registrar) {
        this.registrar = registrar;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }




}


