package database.classes;
// Generated 19-May-2016 11:52:48 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;




/**
 * Game generated by hbm2java
 */
public class Game  implements java.io.Serializable {


     private Integer id;
     private String navn;
     private String boardgamegeekId;
     private Integer antall;
     private Selskap selskap;
     private Integer orgId;
     private Set<Gamesession> sesjoner = new HashSet<Gamesession>(0);
     private Set<Rating> rangeringer = new HashSet<Rating>(0);

    public Game() {
    }

    public Game(String navn, String boardgamegeekId, Integer antall, Selskap selskap, Integer orgId) {
       this.navn = navn;
       this.boardgamegeekId = boardgamegeekId;
       this.antall = antall;
       this.selskap = selskap;
       this.id = orgId;
    }
   
    public Integer getId() {
        return this.id;
    }   
    public void setId(Integer id) {
        this.id = id;
    }
    public void setSesjoner(Set<Gamesession> lis) {
        this.sesjoner = lis;
    }
    public Set<Gamesession> getSesjoner() {
        return this.sesjoner;
    }    
    public void setRangeringer(Set<Rating> lis) {
        this.rangeringer = lis;
    }
    public Set<Rating> getRangeringer() {
        return this.rangeringer;
    }      
    public String getNavn() {
        return this.navn;
    }
    
    public void setNavn(String navn) {
        this.navn = navn;
    }
    public String getBoardgamegeekId() {
        return this.boardgamegeekId;
    }
    
    public void setBoardgamegeekId(String boardgamegeekId) {
        this.boardgamegeekId = boardgamegeekId;
    }
    public Integer getAntall() {
        return this.antall;
    }
    
    public void setAntall(Integer antall) {
        this.antall = antall;
    }
    public Selskap getSelskap() {
        return this.selskap;
    }
    
    public void setSelskap(Selskap selskap) {
        this.selskap = selskap;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }




}


