package database.classes;
// Generated 19-May-2016 11:52:48 by Hibernate Tools 4.3.1



/**
 * Participation generated by hbm2java
 */
public class Participation  implements java.io.Serializable {


     private Integer id;
     private Player spiller;
     private Float poeng;
     private Integer posisjon;
     private Gamesession spillsesjon;
     private Faction fraksjonId;

    public Participation() {
    }

    public Participation(Player spillerId, Gamesession sesjonId, Float poeng, Integer posisjon, Integer pod, Faction tfac) {
       this.spiller = spillerId;

       this.spillsesjon = sesjonId;
       this.poeng = poeng;
       this.posisjon = posisjon;
       this.id = pod;
       this.spillsesjon = sesjonId;
       this.fraksjonId = tfac;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Player getSpiller() {
        return this.spiller;
    }
    
    public void setSpiller(Player spillerId) {
        this.spiller = spillerId;
    }
    public Faction getFraksjonId() {
        return this.fraksjonId;
    }
    
    public void setFraksjonId(Faction fraksjonId) {
        this.fraksjonId = fraksjonId;
    }
    public Gamesession getSpillsesjon() {
        return this.spillsesjon;
    }
    
    public void setSpillsesjon(Gamesession sesjonId) {
        this.spillsesjon = sesjonId;
    }
    public Float getPoeng() {
        return this.poeng;
    }
    
    public void setPoeng(Float poeng) {
        this.poeng = poeng;
    }
    public Integer getPosisjon() {
        return this.posisjon;
    }
    
    public void setPosisjon(Integer posisjon) {
        this.posisjon = posisjon;
    }




}


