package database.classes;
// Generated 19-May-2016 11:52:48 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;




/**
 * Player generated by hbm2java
 */
public class Player  implements java.io.Serializable {


     private Integer id;
     private String fornavn;
     private String etternavn;
     private String facebookId;
     private String epost;
     private String brukernavn;
     private String passord;
     private Integer rettighet;
     private Integer orgId;
     private Integer ignore;
     private Set<Participation> deltakelser = new HashSet<Participation>(0);
     private Set<Rating> rangeringer = new HashSet<Rating>(0);

    public Player() {
    }

    public Player(String fornavn, String etternavn, String facebookId, String epost, String brukernavn, String passord, Integer rettighet, Integer orgId, Integer tgnore) {
       this.fornavn = fornavn;
       this.etternavn = etternavn;
       this.facebookId = facebookId;
       this.epost = epost;
       this.brukernavn = brukernavn;
       this.passord = passord;
       this.rettighet = rettighet;
       this.id = orgId;
       this.ignore = tgnore;
    }
   
    public Integer getId() {
        return this.id;
    }   
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getIgnore() {
        return this.ignore;
    }   
    public void setIgnore(Integer tugnore) {
        this.ignore = tugnore;
    }    
    public void setDeltakelser(Set<Participation> lis) {
        this.deltakelser = lis;
    }
    public Set<Participation> getDeltakelser() {
        return this.deltakelser;
    }
    public void setRangeringer(Set<Rating> lis) {
        this.rangeringer = lis;
    }
    public Set<Rating> getRangeringer() {
        return this.rangeringer;
    }     
    public String getFornavn() {
        return this.fornavn;
    }
    
    public void setFornavn(String fornavn) {
        this.fornavn = fornavn;
    }
    public String getEtternavn() {
        return this.etternavn;
    }
    
    public void setEtternavn(String etternavn) {
        this.etternavn = etternavn;
    }
    public String getFacebookId() {
        return this.facebookId;
    }
    
    public void setFacebookId(String facebookId) {
        this.facebookId = facebookId;
    }
    public String getEpost() {
        return this.epost;
    }
    
    public void setEpost(String epost) {
        this.epost = epost;
    }
    public String getBrukernavn() {
        return this.brukernavn;
    }
    
    public void setBrukernavn(String brukernavn) {
        this.brukernavn = brukernavn;
    }
    public String getPassord() {
        return this.passord;
    }
    
    public void setPassord(String passord) {
        this.passord = passord;
    }
    public Integer getRettighet() {
        return this.rettighet;
    }
    
    public void setRettighet(Integer rettighet) {
        this.rettighet = rettighet;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }




}


