package database.classes;
// Generated 19-May-2016 11:52:48 by Hibernate Tools 4.3.1



/**
 * Scenario generated by hbm2java
 */
public class Scenario  implements java.io.Serializable {


     private Integer id;
     private String navn;

     private Integer orgId;
     private Game spillet;

    public Scenario() {
    }

    public Scenario(String navn, Game spillId, Integer orgId) {
       this.navn = navn;
       this.spillet = spillId;
       this.id = orgId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNavn() {
        return this.navn;
    }
    
    public void setNavn(String navn) {
        this.navn = navn;
    }
    public Game getSpillet() {
        return this.spillet;
    }
    
    public void setSpillet(Game spillId) {
        this.spillet = spillId;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }




}


