package database.classes;
// Generated 19-May-2016 11:52:48 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;




/**
 * Selskap generated by hbm2java
 */
public class Selskap  implements java.io.Serializable {


     private Integer id;
     private String navn;
     private Integer orgId;
     private Set<Game> spill = new HashSet<Game>(0);

    public Selskap() {
    }

    public Selskap(String navn, Integer orgId) {
       this.navn = navn;
       this.id = orgId;
    }
    
    public void setSpill(Set<Game> lis) {
        this.spill = lis;
    }
    public Set<Game> getSpill() {
        return this.spill;
    }     
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNavn() {
        return this.navn;
    }
    
    public void setNavn(String navn) {
        this.navn = navn;
    }
    public Integer getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }




}


